name: Docker
on:
  push:
    branches:
      - master
  schedule:
  - cron: '54 2 2 * *'
jobs:
  buildDockerImage:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/wisvch/bapc-2020
        tags: type=sha, prefix={{date 'YYYYMMDD'}}-
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.ref == 'refs/heads/master' }}
